# Shared test setup for mfsusieR.
#
# Provides:
#   - mfsusier_test_seed()          : the canonical RNG seed used by every
#                                     fidelity test, so seeds are not
#                                     scattered through individual files.
#   - mfsusier_load_fixture(name)   : loads a fixture .rds from
#                                     tests/testthat/fixtures/<name>.rds.
#                                     Skips the calling test if the fixture
#                                     is missing (it is generated by
#                                     tests/testthat/scripts/make-fixtures.R).
#   - skip_if_no_mvf_alpha()        : skip helper for the apple-to-apple
#                                     fidelity tests that compare against
#                                     `mvf.susie.alpha::multfsusie`.

mfsusier_test_seed <- function() {
  1L
}

mfsusier_load_fixture <- function(name) {
  path <- testthat::test_path("fixtures", paste0(name, ".rds"))
  if (!file.exists(path)) {
    testthat::skip(paste0(
      "Fixture '", name, "' not found at ", path,
      ". Run tests/testthat/scripts/make-fixtures.R to generate it."
    ))
  }
  readRDS(path)
}

skip_if_no_mvf_alpha <- function() {
  testthat::skip_if_not_installed("mvf.susie.alpha")
}
