# Generated by cpp11: do not edit by hand

hmm_forward_cpp <- function(emit, P, pi, t1_normalize) {
  .Call(`_mfsusieR_hmm_forward_cpp`, emit, P, pi, t1_normalize)
}

hmm_backward_cpp <- function(emit, P) {
  .Call(`_mfsusieR_hmm_backward_cpp`, emit, P)
}

hmm_xi_cpp <- function(alpha_hat, beta_hat, emit, P) {
  .Call(`_mfsusieR_hmm_xi_cpp`, alpha_hat, beta_hat, emit, P)
}

mixture_log_bf_per_scale_cpp <- function(bhat, shat, sd_grid, pi_grid, v_scale) {
  .Call(`_mfsusieR_mixture_log_bf_per_scale_cpp`, bhat, shat, sd_grid, pi_grid, v_scale)
}

mixture_posterior_per_scale_cpp <- function(bhat, shat, sd_grid, pi_grid, v_scale) {
  .Call(`_mfsusieR_mixture_posterior_per_scale_cpp`, bhat, shat, sd_grid, pi_grid, v_scale)
}
