# Generated by cpp11: do not edit by hand

mixture_log_bf_per_scale_cpp <- function(bhat, shat, sd_grid, pi_grid, v_scale) {
  .Call(`_mfsusieR_mixture_log_bf_per_scale_cpp`, bhat, shat, sd_grid, pi_grid, v_scale)
}

mixture_posterior_per_scale_cpp <- function(bhat, shat, sd_grid, pi_grid, v_scale) {
  .Call(`_mfsusieR_mixture_posterior_per_scale_cpp`, bhat, shat, sd_grid, pi_grid, v_scale)
}
