# Documentation for the bundled simulated example datasets. Build
# script: `data-raw/make_data.R`. Each dataset uses the
# `susieR::N3finemapping` LD scaffold for realistic genotype
# correlation and adds explicit known causal effects so that
# vignettes can fit, post-smooth, and plot without external data
# downloads.

#' Simulated methylation QTL example
#'
#' Simulated cis-mQTL data with `n = 100` samples, `p = 12`
#' SNPs, and `T = 32` CpGs. Three causal SNPs (1, 9, 3) act on
#' two CpG clusters: SNPs 1 and 9 affect cluster A (CpGs 9 to
#' 16) with opposite signs, and SNP 3 affects cluster B (CpGs
#' 25 to 32). SNP 4 is a high-LD near-clone of SNP 3.
#'
#' @format A list with components
#' \describe{
#'   \item{`X`}{`n x p` genotype matrix (`p = 12`).}
#'   \item{`Y`}{`n x T` methylation matrix (`T = 32`).}
#'   \item{`pos`}{length-`T` integer vector of CpG indices.}
#'   \item{`causal_snps`}{integer vector `c(1, 9, 3)` of column
#'     indices in `X` that carry true effects.}
#'   \item{`causal_betas`}{`length(causal_snps) x T` matrix of
#'     true per-CpG effects.}
#'   \item{`truth_mask`}{length-3 list of length-`T` boolean
#'     vectors, one per CS, marking the CpGs each CS truly
#'     affects. Read by `mfsusie_plot_lfsr()` when the
#'     `truth` argument is supplied.}
#'   \item{`description`}{free-text description of the dataset.}
#' }
#'
#' @source Simulated. See `data-raw/make_data.R`.
#' @keywords datasets
#' @examples
#' \donttest{
#' data(dnam_example)
#' fit <- fsusie(dnam_example$Y, dnam_example$X,
#'               pos = dnam_example$pos, L = 15, L_greedy = 5, verbose = TRUE)
#' fit_s <- mf_post_smooth(fit, method = "TI",
#'                         wavelet_filter = 1L,
#'                         wavelet_family = "DaubExPhase")
#' mfsusie_plot(fit_s)
#' }
"dnam_example"

#' Simulated RNA-seq cis-eQTL example
#'
#' Simulated cis-eQTL data on a power-of-two exon-body grid:
#' `n = 574` (the full `susieR::N3finemapping$X[, 1:100]` LD
#' scaffold), `p = 100` SNPs, `T = 128` evenly-spaced
#' positions. Two causal SNPs at positions 25 and 75 carry
#' smooth random expression effects generated by
#' wavelet-coefficient shrinkage, matching the smooth-function
#' class assumed by the fSuSiE prior. Used by
#' `vignette("fsusie_intro")`.
#'
#' @format A list with components
#' \describe{
#'   \item{`X`}{`n x p` genotype matrix (`n = 574`, `p = 100`)
#'     sliced from `susieR::N3finemapping$X[, 1:100]`.}
#'   \item{`Y`}{`n x T` expression matrix (`T = 128`).}
#'   \item{`pos`}{length-`T` integer vector of exon-body
#'     positions.}
#'   \item{`causal_snps`}{integer vector `c(25, 75)` of column
#'     indices in `X` that carry true effects.}
#'   \item{`causal_betas`}{`length(causal_snps) x T` matrix of
#'     true per-position effects.}
#'   \item{`description`}{free-text description.}
#' }
#'
#' @source Simulated. See `data-raw/make_data.R`.
#' @keywords datasets
#' @examples
#' \donttest{
#' data(rnaseq_example)
#' fit <- fsusie(rnaseq_example$Y, rnaseq_example$X,
#'               pos = rnaseq_example$pos, L = 15, L_greedy = 5, verbose = TRUE)
#' fit_s <- mf_post_smooth(fit, method = "HMM")
#' mfsusie_plot(fit_s)
#' }
"rnaseq_example"

#' Simulated multi-outcome QTL example
#'
#' Simulated multi-outcome QTL data for `mfsusie()` covering
#' DNA methylation (functional, `T = 64`), RNA-seq (functional,
#' `T = 32`), and two scalar QTLs (eQTL, pQTL). Two causal SNPs
#' shared across all four outcomes; per-outcome shapes and
#' signs differ.
#'
#' @format A list with components
#' \describe{
#'   \item{`X`}{`n x p` genotype matrix (`p = 150`) sliced from
#'     `susieR::N3finemapping$X`.}
#'   \item{`Y_list`}{named list of four outcomes:
#'     `dnam` (n x 64), `rna` (n x 32), `eqtl` (n x 1),
#'     `pqtl` (n x 1).}
#'   \item{`pos_list`}{named list of position vectors (CpG bp,
#'     exon-body indices, scalar dummy `1L` for the QTLs).}
#'   \item{`causal_snps`}{integer vector of shared causal SNPs.}
#'   \item{`description`}{free-text description.}
#' }
#'
#' @source Simulated. See `data-raw/make_data.R`.
#' @keywords datasets
#' @examples
#' \donttest{
#' data(multiomic_example)
#' fit <- mfsusie(multiomic_example$X, multiomic_example$Y_list,
#'                pos = multiomic_example$pos_list, L = 15, L_greedy = 5,
#'                verbose = TRUE)
#' fit_s <- mf_post_smooth(fit, method = "TI",
#'                         wavelet_filter = 1L,
#'                         wavelet_family = "DaubExPhase")
#' mfsusie_plot(fit_s)
#' }
"multiomic_example"

#' Simulated GTEx-style cis-eQTL example
#'
#' Simulated cis-eQTL data inspired by published GTEx case
#' studies (AHCYL1, SCD, HSP90AA1, STMN2, ABHD17A): a
#' functional response on 256 gene-body positions, three
#' causal SNPs with localized peak effects at distinct 5',
#' mid-body, and 3' positions. Used by
#' `vignette("fsusie_gtex_case_study")`.
#'
#' @format A list with components
#' \describe{
#'   \item{`X`}{`n x p` genotype matrix (`p = 200`) sliced from
#'     `susieR::N3finemapping$X`.}
#'   \item{`Y`}{`n x T` log1p-coverage matrix (`T = 256`).}
#'   \item{`pos`}{length-`T` integer vector of gene-body positions.}
#'   \item{`causal_snps`}{integer vector of column indices in
#'     `X` that carry true effects.}
#'   \item{`causal_betas`}{`length(causal_snps) x T` matrix of
#'     true per-position effects.}
#'   \item{`description`}{free-text description.}
#' }
#'
#' @source Simulated. See `data-raw/make_data.R`.
#' @keywords datasets
#' @examples
#' \donttest{
#' data(gtex_example)
#' fit <- fsusie(gtex_example$Y, gtex_example$X,
#'               pos = gtex_example$pos, L = 15, L_greedy = 5,
#'               verbose = TRUE)
#' fit_s <- mf_post_smooth(fit, method = "TI",
#'                         wavelet_filter = 1L,
#'                         wavelet_family = "DaubExPhase")
#' mfsusie_plot(fit_s)
#' }
"gtex_example"
